# Generated by Django 4.1.7 on 2023-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('passage', 'question'), name='unique_for_passage'),
        ),
    ]
