# Generated by Django 4.1.7 on 2023-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answer_unique_for_passage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_for_passage',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('passage', 'question'), name='unique_for_passage', violation_error_message='Ыыфы'),
        ),
    ]
