# Generated by Django 4.2.3 on 2023-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=None, null=True, verbose_name='Значение'),
        ),
    ]
