# Generated by Django 4.2.3 on 2023-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_avg_answers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='avg_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Средний результат'),
        ),
    ]
