# Generated by Django 4.2.3 on 2023-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_avg_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='avg_answers_count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Среднее количество ответов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='avg_correct_answers_count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Среднее количество правильных ответов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='avg_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Средний результат'),
        ),
    ]
