services:

  backend:
    build: backend/
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:15.3-alpine3.18
    env_file:
      - ./backend/.env

  redis:
    image: redis:7.2-rc-alpine3.18
    hostname: redis

  worker:
    build: backend/
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./backend/.env

  worker2:
    build: backend/
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info -Q tests
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./backend/.env

  flower:
    build: backend/
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
