services:

  nginx:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - frontend

  backend:
    build: backend/
    expose:
      - 8000
    volumes:
      - ./backend:/app/backend
      - static_dir:/app/backend/static
      - media_dir:/app/backend/media
    env_file:
      - ./backend/.env
    depends_on:
      - database

  database:
    image: postgres:15.3-alpine3.18
    env_file:
      - ./backend/.env

  redis:
    image: redis:7.2-rc-alpine3.18
    hostname: redis

  worker:
    build: backend/
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./backend/.env

  worker2:
    build: backend/
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info -Q tests
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./backend/.env

  flower:
    build: backend/
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  gpt:
    build: gpt/
    expose:
      - 8501
    volumes:
      - ./gpt:/app/gpt
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8501"

  frontend:
    build: frontend/
    expose:
      - 3000
    command: npm start
    depends_on:
      - backend
      - gpt
    volumes:
      - ./frontend/public/:/usr/src/app/public/
      - ./frontend/src/:/usr/src/app/src/

volumes:
  static_dir:
  media_dir: