services:

  backend:
    build: backend/
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    environment:
      - DB_HOST=database
      - DB_NAME=testify_db
      - DB_USER=testify_db_user
      - DB_PASS=123

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=testify_db
      - POSTGRES_USER=testify_db_user
      - POSTGRES_PASSWORD=123

  redis:
    image: redis:7.2-rc-alpine3.18
    hostname: redis

  worker:
    build: backend/
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend:/app/backend
    links:
      - redis
    depends_on:
      - redis