# Generated by Django 4.1.7 on 2023-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(null=True, verbose_name='Результат')),
                ('codeword', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Кодовое слово')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Прохождение',
                'verbose_name_plural': 'Прохождения',
                'db_table': 'passages',
                'ordering': ['-created'],
            },
        ),
    ]
