# Generated by Django 4.1.7 on 2023-07-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
        ('passages', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='tests.test', verbose_name='Тест'),
        ),
    ]
