# Generated by Django 4.1.7 on 2023-04-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='users',
        ),
    ]
