# Generated by Django 4.1.7 on 2023-05-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='time_create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='time_update',
            new_name='updated',
        ),
    ]
