# Generated by Django 4.1.7 on 2023-04-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_test_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='users',
        ),
    ]
