# Generated by Django 4.1.7 on 2023-04-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_testquestion_user_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswer',
            name='choiced',
        ),
        migrations.RemoveField(
            model_name='testanswer',
            name='users',
        ),
    ]
