# Generated by Django 4.1.7 on 2023-04-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_testanswer_choiced_remove_testanswer_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='procent',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='right_answers',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
