# Generated by Django 4.1.7 on 2023-04-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_testresult_procent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testquestion')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_answers', to='tests.testresult')),
            ],
        ),
    ]
