# Generated by Django 4.1.7 on 2023-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testresultanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
