# Generated by Django 4.1.7 on 2023-04-21 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0009_rename_testanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresultanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='testresultanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testresultanswer',
            name='result',
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.DeleteModel(
            name='TestResultAnswer',
        ),
    ]
