# Generated by Django 4.2.5 on 2023-09-25 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=20, verbose_name='Варианты ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Single choice', 'Одиночный выбор'), ('Multiple choice', 'Множественный выбор'), ('Text input', 'Ввод текста'), ('Matching', 'Установление соответствий'), ('Sequencing', 'Установление последовательности')], default='Single choice', max_length=30, verbose_name='Тип'),
        ),
    ]
