# Generated by Django 4.2.3 on 2023-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
