# Generated by Django 4.2.3 on 2023-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_answer_choices_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Одиночный выбор'), ('MULTIPLE_CHOICE', 'Множественный выбор'), ('TEXT_INPUT', 'Ввод текста'), ('MATCHING', 'Установление соответствий'), ('SEQUENCING', 'Установление последовательности')], default='SINGLE_CHOICE', max_length=30, verbose_name='Тип'),
        ),
    ]
