# Generated by Django 4.1.7 on 2023-03-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
