# Generated by Django 4.1.7 on 2023-04-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_avatar_likedislike_feedback_comment_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='is_dislike',
        ),
    ]
