# Generated by Django 4.1.7 on 2023-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_likedislike_is_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
