# Generated by Django 4.1.7 on 2023-04-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_myuser_email_confirmed_myuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
