# Generated by Django 4.1.7 on 2023-05-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_rename_time_create_test_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relations', '0004_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'test')},
        ),
    ]
