# Generated by Django 4.1.7 on 2023-05-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_relations', '0005_alter_bookmark_test_alter_feedback_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time_update',
            new_name='updated',
        ),
    ]
