# Generated by Django 4.1.7 on 2023-05-20 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_rename_time_create_test_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relations', '0006_rename_time_create_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together={('user', 'question')},
        ),
    ]
